# Generated by Django 5.2.8 on 2025-11-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=25, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('period', models.CharField(help_text="формат 'Апрель 15-16,2024'", max_length=255, verbose_name='Период проведения работ')),
                ('members', models.PositiveIntegerField(default=1, verbose_name='Количество участников')),
                ('trees', models.PositiveIntegerField(default=1, verbose_name='Количество деревьев')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город проведения')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255, verbose_name='Alt-текст')),
                ('photo', models.ImageField(upload_to='car_make/photos/', verbose_name='Фотография')),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='main.history', verbose_name='Карточка истории')),
            ],
            options={
                'verbose_name': 'Фотография для карточки',
                'verbose_name_plural': 'Фотографии для карточек',
            },
        ),
    ]
