# Generated by Django 5.2.8 on 2025-11-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('person', 'Физическое лицо'), ('company', 'ООО')], default='person', max_length=20, verbose_name='Тип регистрации')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО / Название компании')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('company_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес компании')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='content_type',
            field=models.CharField(choices=[('drone', 'Кадры с дрона'), ('report', 'Репортажи')], default='drone', max_length=20, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='historyphoto',
            name='photo',
            field=models.ImageField(upload_to='history/photos/', verbose_name='Фотография'),
        ),
    ]
