# Generated by Django 5.2.8 on 2025-11-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_registration_video_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='created',
            new_name='created_at',
        ),
    ]
